name: Deploy to k3s

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/ilyasjaelani/simple-demoapp

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push image
        id: build_step
        run: |
          # Ambil 7 karakter pertama SHA untuk tagging
          TAG=sha-${{ github.sha }}
          TAG=${TAG:0:11} 
          
          echo "Building $TAG..."
          docker build -t ${{ env.IMAGE }}:$TAG -t ${{ env.IMAGE }}:latest .
          
          docker push ${{ env.IMAGE }}:$TAG
          docker push ${{ env.IMAGE }}:latest
          
          # Simpan tag ke output agar bisa dipakai step berikutnya
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        # ID digunakan untuk mereferensikan output step ini
        
      - name: Deploy to k3s
        run: |
          # Menggunakan tag spesifik (SHA) lebih aman daripada :latest 
          # untuk menghindari caching issue di K8s nodes
          kubectl set image deployment/demoapp \
            demoapp=${{ env.IMAGE }}:${{ steps.build_step.outputs.tag }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/demoapp --timeout=120s

      - name: Verify
        run: |
          kubectl get pods -l app=demoapp